# Lecture 11 Quiz: Logistic Regression & Classification

### **The Scenario**

You are working for a healthcare tech startup. You have a dataset of patients who were tested for a specific condition. Your goal is to move beyond the "blob separation" of GMMs and build a predictive model that estimates the probability of a patient having the condition based on their symptoms. You will implement Logistic Regression and explore the concepts of Generalization and Validation.

### Part 1: Conceptual Stress-Tests

**Question 1: The "S" Curve**

In Linear Regression, we output the raw score $y = \mathbf{w}^T\mathbf{x}$. In Logistic Regression, we pass this output through the **Sigmoid (Logistic) function**:

$$\sigma(z) = \frac{1}{1 + e^{-z}}$$



[Image of Sigmoid function curve]


**Why do we do this?**

A) To make the loss function linear.

B) To squash the output between 0 and 1, allowing it to be interpreted as a probability.

C) To ensure the gradient is always constant.

D) To penalize outliers more heavily than Mean Squared Error does.

#### Answer:
B) To squash the output between 0 and 1, allowing it to be interpreted as a probability. 

explaination - The sigmiod function transforms the raw output of the linear model into a value between 0 and 1 which can be interpreted as the probability of the positive class. This is essential for classification tasks as it allows us to make decisions based on a threshold (commonly 0.5) to classify patients as having or not having the condition.

**Question 2: Generalization & The "Ugly Duckling"**

You train a model on your training set ($D_{Tr}$) and achieve 99% accuracy. However, when you deploy it on the test set ($D_{Te}$), the accuracy drops to 65%. This is a classic problem in machine learning.

**Which of the following is the most likely cause and the most common remedy?**

A) **Underfitting**; increase the model complexity to capture more noise.

B) **High Bias**; collect more training data to simplify the model.

C) **Overfitting**; apply regularization (like $L_1$ or $L_2$ norms) to penalize high weights.

D) **Lucky Split**; no action needed, the test set is simply mathematically distinct.



#### Answer:

C) **Overfitting**; apply regularization (like $L_1$ or $L_2$ norms) to penalize high weights. 

explaination - the significant drop in accuracy from the training set to the test set indicates that the model has likely overfitted the training data capturing noise and specific patterns that do not generalize well to unseen data. regularization techniques like L1 (Lasso) or L2 (Ridge) can help reduce overfitting by adding a penalty term to the loss function which discourages overly complex models and encourages simpler ones that generalize better.

### **Part 2: The Arithmetic of Belief**

**Question 3: The Rare Disease Paradox**

**Scenario:**
A disease is prevalent in only **1%** of the population ($P(D) = 0.01$).
A medical test is **90% accurate** in both directions:
* **True Positive Rate:** $P(+\text{ | } D) = 0.90$
* **True Negative Rate:** $P(-\text{ | } \text{no } D) = 0.90$

**The Test:**
A patient takes the test and it comes back **POSITIVE**.

**Task:**
Calculate the probability that the patient actually has the disease.
$$P(D \text{ | } +) = \frac{P(+ \text{ | } D)P(D)}{P(+)}$$

*Show your calculation steps below using Bayes' Theorem.*

solution :

To calculate $P(D \text{ | } +)$ using Bayes' Theorem, we first need to compute $P(+)$, the total probability of testing positive. We can break down $P(+)$ into two parts: 

1. The probability of testing positive given that the patient has the disease: $P(+ \text{ | } D)P(D)$ 

2. The probability of testing positive given that the patient does not have the disease: $P(+ \text{ | } \text{no } D)P(\text{no } D)$ 

First we calculate $P(\text{no } D)$: $$P(\text{no } D) = 1 - P(D) = 1 - 0.01 = 0.99$$ 

Next we calculate $P(+ \text{ | } \text{no } D)$: 

Since the test is 90% accurate in both directions, the false positive rate is: $$P(+ \text{ | } \text{no } D) = 1 - P(- \text{ | } \text{no } D) = 1 - 0.90 = 0.10$$ 

Now we can compute $P(+)$: $$P(+) = P(+ \text{ | } D)P(D) + P(+ \text{ | } \text{no } D)P(\text{no } D)$$ $$= (0.90)(0.01) + (0.10)(0.99)$$ $$= 0.009 + 0.099$$ $$= 0.108$$ 

Finally, we can apply Bayes' Theorem to find $P(D \text{ | } +)$: $$P(D \text{ | } +) = \frac{P(+ \text{ | } D)P(D)}{P(+)}$$ $$= \frac{(0.90)(0.01)}{0.108}$$ $$= \frac{0.009}{0.108}$$ $$\approx 0.0833$$ 

Thus, the probability that the patient actually has the disease given a positive test result is approximately **8.33%**.

### **Part 3: Coding Challenge — Writing the Logistic Suite**

In this section, you will implement the core optimization logic for two types of classification models.

#### **Task 1: Binary Logistic Regression (Gradient Descent)**
Separate the data into two classes (e.g., "Pass" vs "Fail").

**Formulas for Reference:**

**1. Prediction:** $\hat{y}_i = \sigma(\mathbf{w}^T\mathbf{x}_i)$ \
**2. Gradient Update:** $\mathbf{w} = \mathbf{w} - \eta \frac{1}{N} \mathbf{X}^T (\mathbf{\hat{y}} - \mathbf{y})$

In [16]:
import numpy as np

# --- 1. Setup Synthetic Data ---
np.random.seed(0)
# Features: [Hours Studied, Sleep Quality]
X = np.array([[2, 3], [1, 1], [5, 2], [3, 2], [7, 3], [8, 4]])
# Labels: [Fail, Fail, Pass, Fail, Pass, Pass]
y = np.array([0, 0, 1, 0, 1, 1])

# Add bias term (column of ones)
X_b = np.c_[np.ones((X.shape[0], 1)), X] 

# Initialize weights
w = np.zeros(X_b.shape[1])
learning_rate = 0.1
epochs = 1000

def sigmoid(z):
    # -----------------------------------------------------
    # TODO: Implement the sigmoid function

    return 1 / (1 + np.exp(-z))

    # -----------------------------------------------------

def train_logistic_regression(X, y, w, lr, epochs):
    N = len(y)
    for epoch in range(epochs):
        # -----------------------------------------------------
        # TODO: Implement Gradient Descent
        # 1. Calculate z = Xw
        # 2. Calculate predictions (y_hat) using sigmoid(z)
        # 3. Calculate the gradient: (1/N) * X.T dot (y_hat - y)
        # 4. Update weights: w = w - lr * gradient
        # -----------------------------------------------------
        z = np.dot(X, w)    
        y_hat = sigmoid(z)
        gradient = (1/N) * np.dot(X.T, (y_hat - y))
        w = w - lr * gradient
    return w

final_w = train_logistic_regression(X_b, y, w, learning_rate, epochs)
print(f"Final Weights: {final_w}")

Final Weights: [-3.13971534  2.57346581 -3.33051013]


#### **Task 2: Multi-Class Softmax (The Generalization)**

When we have more than two classes (e.g., Grade A, B, and C), we use the **Softmax function** to ensure the probabilities of all classes sum to 1. This is the multi-class generalization of the logistic function.

**Formula for Reference:**

$$P(y=k | \mathbf{x}) = \frac{e^{\mathbf{w}_k^T \mathbf{x}}}{\sum_{j=1}^K e^{\mathbf{w}_j^T \mathbf{x}}}$$

In [17]:
def softmax(Z):
    """
    Computes the softmax activation for each row of the input matrix.
    
    Z: (N, K) matrix of raw scores (logits) where N is samples, K is classes.
    Returns: (N, K) matrix of probabilities.
    """
    # -----------------------------------------------------
    # TODO: Implement Softmax
    # Hint 1: Use np.exp(Z).
    # Hint 2: Divide each row by its sum to ensure probabilities sum to 1.
    # Numerical Stability Tip: Subtract np.max(Z, axis=1) from Z before exponentiating.
    shift_Z = Z - np.max(Z, axis=1, keepdims=True)
    exp_Z = np.exp(shift_Z)
    
    probs = exp_Z / np.sum(exp_Z, axis=1, keepdims=True)
    return probs

def predict_multi_class(X, W):
    """
    Predicts the class label using the trained weight matrix.
    
    X: (N, d) data matrix.
    W: (d, K) weight matrix where each column represents a class.
    """
    # 1. Calculate raw scores (logits = XW)
    # 2. Apply softmax to get probability distributions
    # 3. Use np.argmax to pick the class with the highest probability

    logits = np.dot(X, W)
    probs = softmax(logits)
    return np.argmax(probs, axis=1)

In [18]:
# 3 samples, 2 features
X_test = np.array([[1, 2], [3, 4], [5, 6]])

# Weights for 3 classes: [Class 0, Class 1, Class 2]
# Dim: (2 features, 3 classes)
W_test = np.array([
    [1, -1, 0],
    [0, 1, -1]
])

probs = softmax(np.dot(X_test, W_test))
predictions = predict_multi_class(X_test, W_test)

print("--- Softmax Probabilities ---")
print(probs)
print("\n--- Predicted Classes ---")
print(predictions)

--- Softmax Probabilities ---
[[4.87855551e-01 4.87855551e-01 2.42888977e-02]
 [8.80090205e-01 1.19107257e-01 8.02538386e-04]
 [9.81997684e-01 1.79859150e-02 1.64010315e-05]]

--- Predicted Classes ---
[0 0 0]
